# Generated by Django 4.0.4 on 2022-07-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
    ]
