# Generated by Django 4.0.4 on 2022-07-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_lesson_image_remove_lesson_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('video', models.FileField(blank=True, upload_to='videos/')),
                ('file', models.FileField(blank=True, upload_to='Files/')),
                ('image', models.ImageField(blank=True, upload_to='Images/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='school.lesson')),
            ],
        ),
    ]
