# Generated by Django 4.0.4 on 2022-07-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_medias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='file',
        ),
    ]
