# Generated by Django 4.0.4 on 2022-07-22 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_lesson_file_lesson_image_lesson_video_delete_medias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-uploaded']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='uploaded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
