# Generated by Django 4.0.4 on 2022-07-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_lesson_options_lesson_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(default='Images/django.jpg', upload_to='Images/sujects/'),
        ),
    ]
