# Generated by Django 4.0.4 on 2022-07-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_subject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='Images/django.jpg', upload_to='Images/courses/'),
        ),
    ]
