# Generated by Django 4.0.4 on 2022-07-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.CharField(default='Hello short lesson description', max_length=250),
        ),
    ]
