# Generated by Django 4.0.4 on 2022-07-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_lesson_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-course']},
        ),
    ]
