# Generated by Django 4.0.4 on 2022-07-24 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_lesson_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=610047)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_room', to='school.course')),
            ],
        ),
    ]
