# Generated by Django 4.0.4 on 2022-07-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_liveclassroom_number_quizz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='no_questions',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='user',
        ),
        migrations.AddField(
            model_name='quizz',
            name='ans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizz',
            name='op1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizz',
            name='op2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizz',
            name='op3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizz',
            name='op4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='liveclassroom',
            name='number',
            field=models.PositiveIntegerField(default=572198),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='question',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
