# Generated by Django 4.0.4 on 2022-07-30 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0016_quizzs_delete_quizz_alter_liveclassroom_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('A', models.CharField(max_length=200, null=True)),
                ('B', models.CharField(max_length=200, null=True)),
                ('C', models.CharField(max_length=200, null=True)),
                ('D', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='liveclassroom',
            name='number',
            field=models.PositiveIntegerField(default=392310),
        ),
        migrations.DeleteModel(
            name='Quizzs',
        ),
    ]
