# Generated by Django 4.0.4 on 2022-08-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_quizs_alter_liveclassroom_number_delete_quizzs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizs',
            name='user',
        ),
        migrations.AlterField(
            model_name='liveclassroom',
            name='number',
            field=models.PositiveIntegerField(default=431492),
        ),
    ]
