# Generated by Django 4.0.4 on 2022-08-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_remove_quizs_user_alter_liveclassroom_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('question', models.CharField(max_length=200)),
                ('A', models.CharField(max_length=200)),
                ('B', models.CharField(max_length=200)),
                ('C', models.CharField(max_length=200)),
                ('D', models.CharField(max_length=200)),
                ('ans', models.CharField(max_length=200)),
                ('lesson', models.ManyToManyField(related_name='mcqs', to='school.lesson')),
            ],
        ),
        migrations.DeleteModel(
            name='Quizs',
        ),
        migrations.AlterField(
            model_name='liveclassroom',
            name='number',
            field=models.PositiveIntegerField(default=472881),
        ),
    ]
