# Generated by Django 4.0.4 on 2022-08-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_mcqs_delete_quizs_alter_liveclassroom_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqs',
            name='lesson',
        ),
        migrations.AddField(
            model_name='mcqs',
            name='course',
            field=models.ManyToManyField(related_name='mcqs', to='school.course'),
        ),
        migrations.AlterField(
            model_name='liveclassroom',
            name='number',
            field=models.PositiveIntegerField(default=676183),
        ),
    ]
