# Generated by Django 4.0.4 on 2022-08-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_mcqs_iterability_alter_liveclassroom_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqs',
            name='course',
        ),
        migrations.AlterField(
            model_name='liveclassroom',
            name='number',
            field=models.PositiveIntegerField(default=100274),
        ),
    ]
