# Generated by Django 4.0.4 on 2022-08-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_remove_mcqs_course_alter_liveclassroom_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCQS',
        ),
        migrations.AlterField(
            model_name='liveclassroom',
            name='number',
            field=models.PositiveIntegerField(default=92291),
        ),
    ]
