# Generated by Django 4.0.4 on 2022-08-20 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_delete_mcqs_alter_liveclassroom_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclassroom',
            name='number',
            field=models.PositiveIntegerField(default=666567),
        ),
        migrations.CreateModel(
            name='MCQS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('question', models.CharField(max_length=200)),
                ('A', models.CharField(max_length=200)),
                ('B', models.CharField(max_length=200)),
                ('C', models.CharField(max_length=200)),
                ('D', models.CharField(max_length=200)),
                ('ans', models.CharField(max_length=200)),
                ('iterability', models.PositiveIntegerField(default=9)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='school.course')),
            ],
        ),
    ]
