# Generated by Django 4.0.4 on 2022-08-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_alter_liveclassroom_number_mcqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqs',
            name='name',
        ),
        migrations.AlterField(
            model_name='liveclassroom',
            name='number',
            field=models.PositiveIntegerField(default=694154),
        ),
    ]
