# Generated by Django 4.0.4 on 2022-08-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_alter_liveclassroom_number_quiz_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclassroom',
            name='number',
            field=models.PositiveIntegerField(default=294701),
        ),
    ]
