# Generated by Django 4.0.4 on 2022-08-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_alter_liveclassroom_number_quiz_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='quiz',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='liveclassroom',
            name='number',
            field=models.PositiveIntegerField(default=492126),
        ),
    ]
